apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.teams: channelName
    notifications.argoproj.io/subscribe.on-deployed.teams: channelName
    notifications.argoproj.io/subscribe.on-health-degraded: channelName
spec:
  project: project-with-role
  source:
    repoURL: https://github.com/csprasanth1/argocd.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

